import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata: Metadata = {
  title: "SYNC - Smart University ID & Access Control Solutions",
  description:
    "Transform your university with next-generation NFC student ID cards. Secure access control, mobile verification, and comprehensive analytics for modern campus management.",
  
  // Optional but recommended for SEO
  keywords: [
    "university ID cards",
    "NFC access control",
    "student identification",
    "campus security",
    "mobile verification",
    "university management system",
    "smart campus solutions",
    "contactless ID cards",
    "student access control",
    "university technology",
  ],
  
  // Branding / authorship
  authors: [{ name: "SYNC Team" }],
  publisher: "SYNC",
  creator: "SYNC",
  
  // Favicon / icons
  icons: {
    icon: "/favicon.ico",
    apple: "/apple-touch-icon.png",
    shortcut: "/favicon.ico",
  },

  // Open Graph for social sharing
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://buysync.co",
    title: "SYNC - Smart University ID & Access Control Solutions",
    description:
      "Transform your university with next-generation NFC student ID cards. Secure access control, mobile verification, and comprehensive analytics for modern campus management.",
    images: [
      {
        url: "/og-image.png",
        width: 1200,
        height: 630,
        alt: "SYNC - Smart University ID Solutions",
      },
    ],
  },

  // Twitter Card
  twitter: {
    card: "summary_large_image",
    title: "SYNC - Smart University ID & Access Control Solutions",
    description:
      "Transform your university with next-generation NFC student ID cards. Secure access control, mobile verification, and comprehensive analytics.",
    images: ["/og-image.png"],
    creator: "@buy_sync",
  },

  // Robots
  robots: {
    index: true,
    follow: true,
  },
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black`}
      >
        {children}
      </body>
    </html>
  );
}
